# Generated by Django 3.1.6 on 2021-02-10 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0004_cabeceracomandamodel_cabeceraestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantemodel',
            name='cabecera',
            field=models.OneToOneField(db_column='cabecera_id', on_delete=django.db.models.deletion.CASCADE, related_name='comanda_cabecera', to='Facturacion.cabeceracomandamodel', verbose_name='Comanda'),
        ),
    ]
